"""
Streaming module for ARGUS AI multi-stream and Phase 4 optimization.
"""

from streaming.buffer_queue import BufferQueue
from streaming.camera_scheduler import CameraScheduler
from streaming.deployment_readiness import (
    AdaptiveInferencePolicy,
    AdmissionDecision,
    AdmissionResult,
    CameraAdmissionController,
    DeploymentMode,
    DeploymentReadinessManager,
    GPUMemoryGuard,
    HardwareCapabilityDetector,
    HardwareCapabilityReport,
    InferenceQualityMode,
    ModelProfileRegistry,
    ModelResourceProfile,
    NetworkBandwidthEstimator,
    ProductionCapacityEstimator,
    RuntimeParameters,
    SecurityAuditor,
    StorageSafetyAuditor,
    SystemProfile,
    SystemProfileEngine,
)
from streaming.frame_dropper import FrameDropper
from streaming.load_balancer import CameraLoadBalancer
from streaming.multi_stream_engine import MultiStreamEngine
from streaming.performance_optimizer import PerformanceOptimizer
from streaming.production_multicamera_engine import (
    CentralStreamScheduler,
    FramePacket,
    HardwareProfile,
    ProductionMultiCameraEngine,
    StreamIngestionQueue,
    detect_hardware_profile,
)
from streaming.production_runtime import (
    AdaptiveResourceManager,
    CameraState,
    CameraStateMachine,
    CapacityEstimator,
    DataPoisoningGuard,
    FPSGovernor,
    FPSPolicy,
    FrameQualityGate,
    GracefulShutdownManager,
    ProductionSurveillanceRuntime,
    ReconnectEngine,
    ResilientWorkerPool,
    SafeModelSwapper,
    StructuredEventLogger,
)
from streaming.worker_pool import CameraWorkerPool

__all__ = [
    "AdaptiveInferencePolicy",
    "AdaptiveResourceManager",
    "AdmissionDecision",
    "AdmissionResult",
    "BufferQueue",
    "CameraAdmissionController",
    "CameraLoadBalancer",
    "CameraScheduler",
    "CameraState",
    "CameraStateMachine",
    "CameraWorkerPool",
    "CapacityEstimator",
    "CentralStreamScheduler",
    "DataPoisoningGuard",
    "DeploymentMode",
    "DeploymentReadinessManager",
    "FPSGovernor",
    "FPSPolicy",
    "FrameDropper",
    "FramePacket",
    "FrameQualityGate",
    "GPUMemoryGuard",
    "GracefulShutdownManager",
    "HardwareCapabilityDetector",
    "HardwareCapabilityReport",
    "HardwareProfile",
    "InferenceQualityMode",
    "ModelProfileRegistry",
    "ModelResourceProfile",
    "MultiStreamEngine",
    "NetworkBandwidthEstimator",
    "PerformanceOptimizer",
    "ProductionCapacityEstimator",
    "ProductionMultiCameraEngine",
    "ProductionSurveillanceRuntime",
    "ReconnectEngine",
    "ResilientWorkerPool",
    "RuntimeParameters",
    "SafeModelSwapper",
    "SecurityAuditor",
    "StorageSafetyAuditor",
    "StreamIngestionQueue",
    "StructuredEventLogger",
    "SystemProfile",
    "SystemProfileEngine",
    "detect_hardware_profile",
]
